name: GH-build-DEV

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-24.04 # siempre explicitar la version del Sistema Operativo

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
         dotnet-version: | # 8.0.x son versiones LTS
            8.0.x  
            9.0.x
    - name: Restore dependencies
      run: dotnet restore
      # 1. debe compilar código fuente del proyecto para verificar que este compile correctamente (sin errores)
    - name: Build
      run: dotnet build --no-restore
      # 2. ejecutar los test unitarios
    - name: Test
      run: dotnet test --no-build --verbosity normal
    
      
      # 3. consumir secrets previamente definidos y enviar un email notificando la finalizacion de ejecucion del workflow
    - name: Send mail
      uses: dawidd6/action-send-mail@v6      
      with:                
        # Required mail server address if not connection_url:
        server_address: ${{ secrets.EMAIL_HOST }}
        # Server port, default 25:
        server_port: ${{ secrets.EMAIL_PORT }}        
        # Optional (recommended) mail server username:
        username: ${{secrets.EMAIL_USERNAME}}
        # Optional (recommended) mail server password:
        password: ${{secrets.EMAIL_PASSWORD}}
        # Required mail subject:
        subject: Test Github Actions Send Email
        # Required recipients' addresses:
        to: ramonarielet12d1@gmail.com
        # Required sender full name (address can be skipped):
        from: Ramon Lugones
        # Optional plain body:
        body: Build job of ${{github.repository}} completed successfully!    
